# Generated by Django 3.0.5 on 2020-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200502_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
