# Generated by Django 3.0.5 on 2020-05-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200503_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_password',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
