# Generated by Django 3.0.5 on 2020-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200503_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_password2',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
