# Generated by Django 3.0.5 on 2020-05-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user__password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
